CREATE TABLE users (
	user_id		INTEGER			NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	username		VARCHAR(100)	NOT NULL,
	email			VARCHAR(100)	NOT NULL,
	password		VARCHAR(100)	NOT NULL,
	salt			CHAR(4), 
	created_date	DATETIME		NOT NULL	DEFAULT NOW(),
	updated_date	DATETIME		NOT NULL	DEFAULT NOW()	ON UPDATE NOW()
);

